### ISSUE TITLE
Implementing interface not working

### ISSUE THREAD

**Issue by goldenice** [sidorares/node-dbus#106]
I tried to implement an existing interface of the Bluez DBus API, the org.bluez.Agent1 interface. Details of that specific interface can be found [here](https://github.com/pauloborges/bluez/blob/master/doc/agent-api.txt) from line 65 down.

Using the bus.exportInterface() method does not seem to work when later requesting the same object, or trying to invoke one of the methods of the exported object.

I later tried to define my own simple interface, to check if I could export anything at all.

My code so far:

```
this._bus = dbus.systemBus();

this._bus.exportInterface({
  Test: console.log
}, '/test/agent', {
  name: 'test.Agent1',
  methods: {
    Test: [ 's' ]
  }
});

this._bus.getObject('/test/agent', 'test', console.log);
// Or this code:
this._bus.invoke({
  path: '/test/agent',
  destination: 'test',
  'interface', 'test.Agent1',
  signature: 's',
  body: [ 'test' ]
});
```

This consistently returns either write errors or an error 'Didn't write bytes to closed stream'.

Can someone put me on the right track here? My endgoal is to register an object an give the path to the Bluez AgentManager, so my (in NodeJS defined) methods get called when bluetooth events happen. Am I thinking in the right direction here?

**Comment by sidorares** [comment]
how do you associate 'test' service name with your object? You need to call `this._bus.requestName(name, 0);` to change from auto-generated name to something you'll use - see https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-request-name

Note that you might need to configure daemon to allow this (session bus might have less restrictions) - see https://github.com/sidorares/node-dbus/blob/master/examples/com.github.sidorares.dbus.Example.conf config example )

**Comment by goldenice** [comment]
Hmm, I tried your suggestion, but it doesn't seem to work. There is a tool available that does exactly this without requesting permission, so I can't imagine that's the issue. Would you happen to know any documentation about implementing an interface provided by another package, instead of your own, because I can't seem to find anything about this :/

**Comment by sidorares** [comment]
> suggestion, but it doesn't seem to work.

Are you able to change the name of your connection with `requestName()`? You should be able to see result with d-feet ( if successful you'll see name in the list of services )

**Comment by goldenice** [comment]
If only it was that easy :stuck_out_tongue:  Haven't found an option in dfeet yet to inspect remote devices. I'm writing code for a headless device (think Raspberry Pi-like) so using dfeet isn't really an option sadly.

**Comment by sidorares** [comment]
debug first on a local device? Also If you can ssh to it with a bit of socat magic you could forwar local port to device and set dbus conection string for d-feet to point there

**Comment by goldenice** [comment]
That might work, but I'd have to set up a VM, as I'm working on OS X for development. I'll try to get that running properly then...

**Comment by sidorares** [comment]
I'm on osx as well, I have local dbus-daemon via homebrew but prefer to test in linux/virtualbox

**Comment by nschoe** [comment]
I know I'm coming late on this, but I was wondering if you could work on it @goldenice or if you had given up?

First you need to know that the system bus is "special" in the sense that it is _very_ restricted: you can't do whatever you want on it.

So just to eliminate the possibility that the error comes from the permission, can you replace `this._bus = dbus.systemBus();' with `this._bus = dbus.sessionBus();` in your test and see if you can get to request the function.

Then, the error you get 'Didn't write bytes to closed stream` means the stream was not opened yet, which means you don't have actual connectivity to the bus (which is why I suspect this is a permission problem on the system bus, but I can't be sure).

So can you try the same code (your fake service test, not the bluez one obvioulsy) on the session bus and tell us if this works?

**Comment by goldenice** [comment]
I'm not quite sure what fixed it, because the responsibility for the bluetooth part of our product was moved away from me. I asked my successor what he changed to my code, and he told me that I didn't have my type signatures right. Eventually, this code seems to work:

```
var agent = {
    mode: "KeyboardDisplay",
    Registered: function(err) {
        console.log('Registered agent', arguments);
    },
    Release: function() {
        console.log('Release', arguments);
    },
    RequestPinCode: function(device) {
        console.log("RequestPinCode", arguments);
    },
    DisplayPinCode: function(device, pincode) {
        console.log("DisplayPinCode", arguments);
    },
    RequestPasskey: function(device) {
        console.log("RequestPasskey", arguments);
    },
    DisplayPasskey: function(device, passkey, entered) {
        console.log("DisplayPasskey", arguments);
    },
    RequestConfirmation: function(device, passkey) {
        console.log("RequestConfirmation", arguments);
    },
    RequestAuthorization: function(device) {
        console.log("RequestAuthorization", arguments);
    },
    AuthorizeService: function(device, uuid) {
        console.log("AuthorizeService", arguments);
    },
    Cancel: function() {
        console.log("Cancel", arguments);
    },
};

bus.exportInterface(agent, AGENTPATH, {
        name: 'org.bluez.Agent1',
        methods: {
            Release:                [ '', '' ],
            RequestPinCode:         [ 'o', 's' ],
            DisplayPinCode:         [ 'os', '' ],
            RequestPasskey:         [ 'o', 'u' ],
            DisplayPasskey:         [ 'ouq', '' ],
            RequestConfirmation:    [ 'ou', '' ],
            RequestAuthorization:   [ 'o', '' ],
            AuthorizeService:       [ 'os', '' ],
            Cancel:                 [ '', '' ]
        }
    });

var bluez = bus.getService('org.bluez');
    bluez.getInterface('/org/bluez', 'org.bluez.AgentManager1', function(err, agentmanager) {
       agentmanager.RegisterAgent(AGENTPATH, agent.mode || "NoInputNoOutput", function(err, res) {
           agentmanager.RequestDefaultAgent(AGENTPATH, callback);
        }));
    });
```

So it mostly was the lack of a correct type signature probably, but I can't say for sure.

**Comment by nschoe** [comment]
Okay, without the original code it's difficult to say :-P
I'm closing this since it seems to be resolved.

Thank you @goldenice for answering back so fats after all this time :-)
