### ISSUE TITLE
Basic getInterface() nonfunctional

### ISSUE THREAD

**Issue by rektide** [sidorares/node-dbus#110]
`dbus-send --session --type=method_call --print-reply --dest=org.PulseAudio1 / org.freedesktop.DBus.Introspectable.Introspect` returns due xml and so should the following, but it does not (err is `[Error: No such interface found]`):

```
const
  dbus= require("dbus-native"),
  bus= dbus.sessionBus(),
  service= bus.getService("org.PulseAudio1")

service.getInterface(
	"/",
	"org.freedesktop.DBus.Introspectable",
	function(err, iface){
	   console.log(arguments)
	}
)
```

I'd expect the interface is found, and the result is (as it is in the command line dbus-send),
```
<!DOCTYPE node PUBLIC "-//freedesktop//DTD D-BUS Object Introspection 1.0//EN"
"http://www.freedesktop.org/standards/dbus/1.0/introspect.dtd">
<node>
  <node name="org"/>
</node>
```

**Comment by sidorares** [comment]
yes, looks like right now getInterface does not try to find object path recursively ( though I'm sure it was doing something similar), and there is no "/" object for `org.PulseAudio1` service.

If you try same with full object path - `/org/pulseaudio/server_lookup1` you'll get response

**Comment by sidorares** [comment]
hi @rektide - could you try master now?

**Comment by rektide** [comment]
No change. The introspection result returned doesn't return an Introspectable interface, even though I just called it as an Introspectable to get said introspection record. I guess this makes `getInterface` not suitable for tree walking, which is probably ok; I'll be able to pickup the low level interface to do this work adequately.
