### ISSUE TITLE
error when using wpa_supplicant

### ISSUE THREAD

**Issue by TheMSB** [sidorares/node-dbus#113]
I am having trouble using dbus-native to utilise wpa_supplicant. Fetching the service seems to go well but after that it seems the service breaks. I commented the code with the unexpected behaviours. Is this a bug in dbuss-native or am I failing in utilising it? 

```js
var dbus = require('dubs-native');
var util = require('util');

var bus = dbus.systemBus();
var wpas = bus.getService('fi.w1.wpa_supplicant1');

var wpai = wpas.getInterface('/fi/w1/wpa_supplicant1'
    , 'fi.w1.wpa_supplicant1', function (err, iface) {
        //console.log(err, face);


        iface.on('PropertiesChanged', function(dict) {
            console.log('interface properties have changed!');
            console.log(dict);
        });

        iface.on('InterfaceAdded', function(path, dict) {
            console.log('interface has been added!');
            console.log(path, dict);
        });

        iface.on('InterfaceRemoved', function(path) {
            console.log('interface has been removed!');
            console.log(path);
        });

        // wpa_supplicant denies knowledge of the interface
        iface.GetInterface('wlan0', function (err, iface2) {
            console.log(err, iface2);
        });

        // console.log(util.inspect(iface, true, 3));

        // Returns 1
        console.log(iface.Interfaces.length);
        // Returns undefined
        console.log(iface.Interfaces[0]);

        // throws error: invalid struct data
        iface.CreateInterface('wlan1', function (err, iface3){
            console.log(err, iface3);
        });
    });
```

**Comment by sidorares** [comment]
according to https://w1.fi/wpa_supplicant/devel/dbus.html

`CreateInterface` signature is `a{sv}` - array of dict entries (string, variant). It takes 1 parameter, which itself is an array. I guess the call should look like

```js
        // [  <- array
        //    [ <- dict entry
        //        'Ifname' <- 's' field of dict entry, a key
        //         [ 's',      <- variant - array with two elements - signature + value
        //            'wlan1'  <- variant value
        //         ] <- end of variant
        //     ] <- end of dict
         //  ] <- array 
        iface.CreateInterface([['Ifname', ['s', 'wlan1]]], function (err, iface3){
            console.log(err, iface3);
        });
```

**Comment by TheMSB** [comment]
Thanks for pointing out my mistake with the CreateInteface interface. I am still however trying to access the list of known interfaces.

```
//Returns [Function]
console.log(iface.Interfaces);
//Throws err not a function
console.log(iface.Interfaces());
```

I am still puzzled how this behaviour is occurring, perhaps I am reading the interface documentation wrongly?

**Comment by TheMSB** [comment]
For clarification: I am still unable to acces my wlan0 interface through wpa_supplicant using the dbus-native module. I have verified that wpa_supplicant is up and running by manually setting up the entire wifi connection using wpa_supplicant terminal commands.

Yet when I try any of the following I still get errors:

```
// wpa_supplicant denies knowledge of the interface
        iface.GetInterface('wlan0', function (err, iface2) {
            console.log( arguments );
            console.log(err, iface2);
        });

        //error couldn't grab interface
        iface.CreateInterface([
            ['Ifname',
                ['s', 'wlan0']
            ]
        ], function (err, iface3){
            console.log(err, iface3);
        });

        //error couldn't grab interface
        iface.CreateInterface([
            ['Ifname',
                ['s', 'wlan0']
            ],
            ['Driver',
                ['s', 'nl80211']
            ],
            ['ConfigFile',
                ['s', '~/etc/wpa_supplicant/wpa_supplicant.conf']
            ]
        ], function (err, iface3){
            console.log(err, iface3);
        });
```

**Comment by sidorares** [comment]
Maybe you need `fi.w1.wpa_supplicant1.Interface.Scan` method?

https://w1.fi/wpa_supplicant/devel/dbus.html#dbus_interface

```js
var wpai = wpas.getInterface('/fi/w1/wpa_supplicant1'
    , 'fi.w1.wpa_supplicant1.Interface', function (err, iface) {
       iface.Scan(/* .... */)   
    });
}
```

Looks like you communicating with wpa_supplicant correctly, so it's more wpa_supplicant dbus api issue, not exactly this library issue.

If you know tool that does the same over dbus api you could capture message exchange

**Comment by TheMSB** [comment]
Thank you for your reply, I also tried the Scan method you suggested but this too leads to a dead end: 

```
var wpai = wpas.getInterface('/fi/w1/wpa_supplicant1'
            , 'fi.w1.wpa_supplicant1.Interface', function (err, iface) {
                iface.Scan([['Type',
                    ['s', 'active']
                ]]);
            });
```

Results in a TypeError: iface.Scan is not a function.
If you have suggestions for a tool that can capture the message exchange on a command line only linux variant those would also be welcome.

**Comment by sidorares** [comment]
I used this library as a logging proxy in the past, I'll try to find code and add under ./bin or ./tools

Basically it forwards port but serialises and prints all messages at the same time using this library's protocol parser

**Comment by TheMSB** [comment]
That would be really helpful, thanks!

**Comment by TheMSB** [comment]
As an update I tried the following:

```
   wpas.getInterface('/fi/w1/wpa_supplicant1', 'org.freedesktop.DBus.Properties', function(err, device) {
                    device.GetAll('fi.w1.wpa_supplicant1', function(err, prop) {
                        var props = arrToMap(prop);
                        console.log(err,props);
                    });
                });

    function arrToMap(arr) {
        var output = {};
        for (var i = 0; i < arr.length; i++) {
            output[arr[i][0]] = arr[i][1][1][0];
        }
        return output;
    }
```

The output:

```
{ DebugLevel: 'info',
  DebugTimestamp: false,
  DebugShowKeys: false,
  Interfaces: [],
  EapMethods: 
   [ 'MD5',
     'TLS',
     'MSCHAPV2',
     'PEAP',
     'TTLS',
     'GTC',
     'OTP',
     'SIM',
     'LEAP',
     'PSK',
     'AKA',
     'AKA\'',
     'FAST',
     'PAX',
     'SAKE',
     'GPSK',
     'WSC',
     'IKEV2',
     'TNC',
     'PWD',
     'EKE' ],
  Capabilities: [ 'ap', 'ibss-rsn', 'p2p' ],
  WFDIEs: { type: 'Buffer', data: [] } }
```

Clearly the Interfaces property is empty but since my wifi is running (and is managed by wpa_supplicant) I can only assume that dbus is not notified when wpa_supplicant sets up the new connection.

**Comment by sidorares** [comment]
can you check that this is consistent when using other clients communicating via dbus?

**Comment by TheMSB** [comment]
> can you check that this is consistent when using other clients communicating via dbus?

If you have suggestions on what to try I'd be willing to, I am running embedded Linux and the amount of services running on it is minimal.

As an update I tried rewriting my entire code using promises to ensure that all my references are initialised but I remain stuck on the following error:

[ 'wpa_supplicant couldn\'t grab this interface.' ]

that is thrown after this section:

```
// creates the interface with wlan0 name and default settings
        iface2.CreateInterface([
            ['Ifname',
                ['s', 'wlan1']
            ]
        ], function (err, iface3){
            //WE ARE CRASHING HERE
            console.log(err, iface3);
        });
```

and I can't seem to find this error in the API specification either leaving me with little hints as to where my problem could be.

**Comment by TheMSB** [comment]
I figured out that because of an older file at: /run/wpa_supplicant/wlan0 wpa_supplicant would throw the error. Removing it solved the problem.

**Comment by gobftald1** [comment]
You saved my life to show the direction where my similar problem also happened. It is about how launching wpa_supplicant. In some OS the default launch is with -u option enabling DBus control interface, other system launch with -C option which opens a unix socket (/run/wpa_supplicant/wlan0)  for wpa_cli program to control and monitor wpa_supplicant running as a daemon.
