### ISSUE TITLE
Invalid struct data - how to implement 'a{sv}' and 'as'?

### ISSUE THREAD

**Issue by Quacky2200** [sidorares/node-dbus#121]
Hello there, 
I have an issue with a 'a{sv}' type? I need this for the mpris MediaPlayer2.Player freedesktop specification? Any help would be great.

The problem is with the Metadata property in the instance, I simply can't get it to work and get an invalid struct data error
![screenshot from 2016-08-30 16-39-13](https://cloud.githubusercontent.com/assets/4623599/18095913/6851e886-6ed0-11e6-8fd7-1797bc8d31d7.png)

While I'm asking, I have one other (small) issue. When I have an array of strings for SupportedMimeTypes/SupportedUriSchemes it comes out as ['h','t','t','p'] instead of ['http']
![screenshot from 2016-08-30 16-37-31](https://cloud.githubusercontent.com/assets/4623599/18095929/755e5514-6ed0-11e6-81d7-12dfcda66b74.png)
![screenshot from 2016-08-30 16-37-59](https://cloud.githubusercontent.com/assets/4623599/18095930/756222f2-6ed0-11e6-917d-70da7daebdc7.png)
![screenshot from 2016-08-30 16-45-33](https://cloud.githubusercontent.com/assets/4623599/18096157/35b46b50-6ed1-11e6-9a7d-0404fb4c7ab9.png)

These are the schemes:
https://specifications.freedesktop.org/mpris-spec/2.2/
https://specifications.freedesktop.org/mpris-spec/2.2/Media_Player.html
https://specifications.freedesktop.org/mpris-spec/2.2/Player_Interface.html

**Comment by Quacky2200** [comment]
I implemented this functionality in my application without the need for this library, and used another so it could be implemented faster.

**Comment by martpie** [comment]
@Quacky2200 May I know which library did you use? :)
