### ISSUE TITLE
How to create and use signals from the server (as well as properties)?

### ISSUE THREAD

**Issue by nschoe** [sidorares/node-dbus#124]
Could you provide an example how to export several signals when I design a DBus service?
The only example I see, rely on the `emit` property of the `iface` object. But I'm not sure this is the end of the story because it seems to work for only one signal, or maybe (but I hope not :/), in the `emit` function we have to `switch..case` on the first argument, which is the name of the signal?

That sounds fishy, am I missing something?

I've seen that using signals from the client is easy, it's something like

```Javascript
sessionBus.getService ('service.name').getInterface ('/path/to/Iface', 'name.of.iface', (e, iface) => {
    if (e) {
        console.error ('Did not get interface: ' + e)
        return
    }

    iface.on ('SignalName', (arg1, arg2) => {
        console.log ('Signal \'SignalName\' fired with args: ' + arg1 + ' - ' + arg2)
    }
})
```

As I'm in, can you show how to get and set a property? In the previous code, when I `console.log` the `iface` object, I've got something like `PropertyName [Getter/Setter]` ~~but I don't know how to actually get or set the property? Am I missing something obvious?~~

Okay so getting the property was easy after all, it is just a callback, it's used like this (including for people wondering the same thing):

```Javascript
sessionBus.getService ('service.name').getInterface ('/path/to/Iface', 'name.of.iface', (e, iface) => {
    if (e) {
        console.error ('Did not get interface: ' + e)
        return
    }

    iface.PropertyName ( (e, propValue) => {
        if (e) {
            console.error ('Could not get propery value: ' + e)
            return
        }

       console.log ('Property value is: ' + propValue)
    })
}
```
So it's easy.

How to **set** it, though? I have tried `PropertyName = 'value'` (with my `PropertyTest`'s type being `s`, so it should work but I still get an error). So any chance you might drop an example?

Thanks in advance! (x2)

**Comment by sidorares** [comment]
Setting a property should be just `iface.PropName = value` - see the code here https://github.com/sidorares/node-dbus/blob/7efa5207af537e1108fd4f2a9311f9b246c5aa9e/lib/introspect.js#L164-L173 Is that code called when you assign value? Which error are you getting?

Yes, emitting signal is done via "emit" - https://github.com/sidorares/node-dbus/blob/7efa5207af537e1108fd4f2a9311f9b246c5aa9e/lib/bus.js#L204-L235
first argument is signal name, rest goes to signal body. Not sure I follow the question re switch/case - can you do `myService.emit('somethingHappened', "param1", 1, 2)`. Note that when you emit something the name should match to what you have in your interface description (it's used to get signature of signal body) - https://github.com/sidorares/node-dbus/blob/7efa5207af537e1108fd4f2a9311f9b246c5aa9e/lib/bus.js#L214

**Comment by nschoe** [comment]
Hi @sidorares , thanks for answering quickly.
So, about `set`ting a property, indeed, this code gets called, **but** I think you left a little surprise in the code^^ I can set a property with `iface.PropName = value` indeed, but **then**, _after_ I have set it and try to get it back (either by calling again the getter or by using `gdbus introspect`) the service crashes. It crashes and says something like:

```Bash
Error: Expected string or buffer argument, got 1234 of type 's'
```

And this is in file [marshall.js:106](https://github.com/sidorares/node-dbus/blob/7efa5207af537e1108fd4f2a9311f9b246c5aa9e/lib/marshall.js#L106). This `1234` bugged me so I did a little `grep -r 1234` at the root of the project and found (this)[https://github.com/sidorares/node-dbus/blob/7efa5207af537e1108fd4f2a9311f9b246c5aa9e/lib/stdifaces.js#L118], ugh!

Is the TODO because you wanted to make some checks before assigning the value, something like checking the type is correct or is there something else?

---

As for the signals, okay, I understand that it's through `emit`, but I find it a bit confusing. Suppose I want to have two signals, I will create my interface description as such:

```Javascript
let ifaceDesc = {
    name: 'test.iface',
    signals: {
        Tick: ['s', 'time'],
        Ping: ['si', 'str', 'number']
    }
}
```
Then I have to create the actual interface object, with the `emit` field. But I'm wondering what should be done inside the `emit` body function. Because as far as I'm concerned, simply creating an empty `emit` function as such:

```Javascript
let iface = {
    emit: function (eventName, ...args) {
        // Empty body function
    }
}
```

I can then fire events with `iface.emit ('Tick', 'Hello, world')` and `iface.emit ('Ping', 'string here', 1089)`. I have confirmed with `gdbus monitor` that the signal gets emitted, and I have made a JS client with the lib and successfully got the event with `on('Tick')` and `on('Ping')`.

But all of this was made with an empty `emit` function body. So I'm wondering: what's the use of the `emit` function in the `iface` object? Besides being called to emit a signal?

As always, thanks for your help!

**Comment by sidorares** [comment]
> Is the TODO because you wanted to make some checks before assigning the value, something like checking the type is correct or is there something else?

No, I just wanted to add actual 'set property' implementation but this was lost somehow. Obviously better to throw "not implemented" exception rather silently doing this, my bad

I'll need to check source code but intention was to inherit from EventEmitter so you don't need to provide `emit` implementation at all. If you have better api please suggest

**Comment by nschoe** [comment]
I'm closing this because the original message was about signals and the problem is solved. I've created issue #129 to discuss specifically about **Set** not being implemented.
