### ISSUE TITLE
Detecting screen lock and unlock events

### ISSUE THREAD

**Issue by bhavyaw** [sidorares/node-dbus#125]
I think we should be able to detect screen lock and unlock with this module.  I read the docs and examples and tried a few examples but wasn't able to get what i wanted.

Corresponding python and command line versions look like this :

**[Python](http://unix.stackexchange.com/a/242304)** 
**[Command line](http://unix.stackexchange.com/questions/28181/run-script-on-screen-lock-unlock)** 

Also, [gnome-screensaver interface docs](https://people.gnome.org/~mccann/gnome-screensaver/docs/gnome-screensaver.html#gs-signals) which emits the required signals.

**Here the code with which I am trying :**

```
var dbus = require('dbus-native');
var conn = dbus();

conn.message({
   path: 'org/gnome/ScreenSaver',
   destination: 'org.gnome.ScreenSaver',
   interface: 'org.gnome.ScreenSaver',
   member: 'ActiveChanged',
   signature: 's',
   body: ["type='signal'"]
});

conn.on('message', function(msg) {
   if (!msg.body)
       return;
       console.log("\n\nInside linux Screen events\n",msg);
});
```

**Comment by sidorares** [comment]
You could probably interact with screensaver at a lower level - see https://github.com/sidorares/node-x11/blob/master/lib/ext/screen-saver.js

let me check org.gnome.ScreenSaver api

Note that you are sending message to `org.gnome.ScreenSaver` service, and you are probably interested in listening messages _from_ service. You need to send AddMatch (this is done automatically when you do `iface.on('your event name' ...)`

Have not checked the code, but you probably need  something like this:

```js
var dbus = require('dbus-native');
var conn = dbus();

conn.addMatch("type='signal',path='org/gnome/ScreenSaver',interface='org.gnome.ScreenSaver',member='ActiveChanged'")


conn.on('message', function(msg) {
  // check path / iface / member
});
```

**Comment by sidorares** [comment]
AddMatch is from standard `org.freedesktop.DBus` interface - 
see https://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-routing
and https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-add-match

**Comment by bhavyaw** [comment]
Thanks for the quick response.

Well as for 

> You could probably interact with screensaver at a lower level - see https://github.com/sidorares/node-x11/blob/master/lib/ext/screen-saver.js

I am sorry but that's way over my head.

> Note that you are sending message to org.gnome.ScreenSaver service, and you are probably interested in listening messages from service. You need to send AddMatch (this is done automatically when you do iface.on('your event name' ...)

I tried this to get the **iface obj** ( interface object on which i can listen to events ) :

```
var dbus = require('dbus-native');
var bus = dbus.sessionBus();

var notify = bus.getService('org.gnome.ScreenSaver');

notify.getInterface('/org/freedesktop/ScreenSaver', 'org.gnome.ScreenSaver', function(e, iface) {
    console.log(e,iface);
});

```

**But this gives me the error :**

```
Error: No such interface found
    at /home/oodles/Documents/projects/productiveOne/productivity-desktop-app/src/node_modules/dbus-native/lib/introspect.js:14:50
    at Parser.<anonymous> (/home/oodles/Documents/projects/productiveOne/productivity-desktop-app/src/node_modules/xml2js/lib/xml2js.js:199:18)
    at emitOne (events.js:90:13)
    at Parser.emit (events.js:182:7)
    at Object.saxParser.onclosetag (/home/oodles/Documents/projects/productiveOne/productivity-desktop-app/src/node_modules/xml2js/lib/xml2js.js:183:24)
    at emit (/home/oodles/Documents/projects/productiveOne/productivity-desktop-app/src/node_modules/sax/lib/sax.js:640:35)
    at emitNode (/home/oodles/Documents/projects/productiveOne/productivity-desktop-app/src/node_modules/sax/lib/sax.js:645:5)
    at closeTag (/home/oodles/Documents/projects/productiveOne/productivity-desktop-app/src/node_modules/sax/lib/sax.js:905:7)
    at Object.write (/home/oodles/Documents/projects/productiveOne/productivity-desktop-app/src/node_modules/sax/lib/sax.js:1449:13)
    at Parser.exports.Parser.Parser.parseString (/home/oodles/Documents/projects/productiveOne/productivity-desktop-app/src/node_modules/xml2js/lib/xml2js.js:211:31) undefined
```

**Comment by sidorares** [comment]
> Any clue regarding "Error: No such interface found" ?

This means there is no such service/interface (you have typo in the name or corresponding service is not started). Can you start [d-feet](https://wiki.gnome.org/action/show/Apps/DFeet?action=show&redirect=DFeet) and check if there is anything similar in list of started services?

**Comment by bhavyaw** [comment]
Its indeed there in list of Session Bus.

![image](https://cloud.githubusercontent.com/assets/6906721/18665725/266881e2-7f46-11e6-838a-156791202e21.png)

**Comment by bhavyaw** [comment]
Done!!

I was looking into the wrong service and the interface. Here's the working code. Thanks a ton for your help and for creating this module.

Also, **d-feet** helped a lot in figuring out the available signals in case of different interfaces. 

```
var dbus = require('dbus-native');
var bus = dbus.sessionBus();
bus.addMatch("type='signal'",function(){});

var notify = bus.getService('com.canonical.Unity');

notify.getInterface('/com/canonical/Unity/Session', 'com.canonical.Unity.Session', function(e, iface) {
    console.log(e,iface);
    iface.on('Locked',function(){
        console.log("\nScreen Locked!!!\n");
    });
    iface.on('Unlocked',function(){
        console.log("\nScreen Unlocked!!!\n");
    });
});
```


PS :
We can add this in examples if we want to. :)

**Comment by sidorares** [comment]
does it work without `bus.addMatch("type='signal'",function(){});`?  When you do `iface.on('Locked', ...` AddMatch is called ( with more specific mask, not "please send all signals to me" )

**Comment by bhavyaw** [comment]
> does it work without bus.addMatch("type='signal'",function(){});?

Yes, it works fine without it.

**Comment by mobiniusHarshajagadish** [comment]
I know I am really late to this conversation. but I am trying to use this method in detecting the locked state in my electron application. I get the below error when I include the code and run my electron app 

App threw an error during load
Error: unknown bus address
    at createStream (/<path to app>/node_modules/dbus-native/index.js:25:26)
    at createConnection (/<path to app>/node_modules/dbus-native/index.js:84:30)

Can some one help me use this on my electron app ? Thanks in advance
