### ISSUE TITLE
Unmarshall error with BlueZ

### ISSUE THREAD

**Issue by sandeepmistry** [sidorares/node-dbus#13]
I'm trying to use dbus-native with the BlueZ DBUS API, getting an error while unmarshalling, here is a gist: https://gist.github.com/sandeepmistry/5330261

I'm new to DBUS, I'll try to figure out what's going on, any help would be greatly appreciated. 

Thanks.

**Comment by jrobeson** [comment]
I'm not sure of the status of this particular issue as it was filed nearly 2 years ago.

**Comment by sidorares** [comment]
@jrobeson me neither. Need to re test examples
A lot of core message parsing issues were fixed since then, but higher level api ( introspection / properties etc is still very low quality and need review )

**Comment by sidorares** [comment]
if you have time to test this that would be great @jrobeson :)

**Comment by jrobeson** [comment]
These examples wouldn't work anymore either, as the bluez API has changed and moved towards a stable API (and is still mostly hidden behind an --experimental flag).  I'm not super familiar with dbus specifics either (except for knowing how it generally works),   I'll try comparing it against how it works vs https://github.com/adafruit/Adafruit_Python_BluefruitLE

**Comment by sidorares** [comment]
heh. I know dbus internals but not that much about BlueZ API

**Comment by jrobeson** [comment]
@sidorares : if you had any inclinations to play along, then you'd need bluez >=5.30, which should contain the complete API.  I think you must also run the bluetoothd with --experimental.

**Comment by jrobeson** [comment]
some changes from bluez 4.x to 5.x that sorta explain the new API http://www.bluez.org/bluez-5-api-introduction-and-porting-guide/

**Comment by jrobeson** [comment]
is thre anything I can provide you with to help out on this (without knowing DBUS all that well). I know that @sandeepmistry's code is not compatible with bluez 5.x , most especially since there's no such thing as a default adapter anymore.  I've done some dbus monitoring, but I'm a little confused at the output of the existing adapter calls. it seems to path of `org.bluez.Adapter1` calls to `/org/bluez/hci0` which would the adapter already. I've cleared the bluetooth cache and restared the service, but still can't ever see what it does when it tries to get the adapter the very first time.

**Comment by jrobeson** [comment]
in case it is useful http://paste.fedoraproject.org/314380/37162221/ , here's a paste of the dbus-monitor output when running this script https://github.com/adafruit/Adafruit_Python_BluefruitLE/blob/master/examples/device_info.py  with the relevant dbus backend calls here: https://github.com/adafruit/Adafruit_Python_BluefruitLE/tree/master/Adafruit_BluefruitLE/bluez_dbus

**Comment by sandeepmistry** [comment]
@sidorares sorry for leaving this issue in a hung state, feel free to close if needed.

**Comment by sidorares** [comment]
@sandeepmistry low level issues are likely fixed, would be good to check original example but if modern bluez api is ahead that might be problematic

**Comment by jrobeson** [comment]
I can say that this is fixed now. You can close it.

**Comment by sidorares** [comment]
thanks @jrobeson !
