### ISSUE TITLE
Using dbust-native on MacOS/OSX

### ISSUE THREAD

**Issue by sebald** [sidorares/node-dbus#131]
Hi,

first of all: I am a total beginner when it comes to `d-bus` :-)

I want to use your library on an MacBook, b/c it is my developing machine. But the result will run on a RaspberryPi. I tried to get your `examples/p2p` to run but I only get the following:

**serv.js**
```
[ 'hello string: ',
  '\u0000AUTH EXTERNAL 353031\r',
  <Buffer 00 41 55 54 48 20 45 58 54 45 52 4e 41 4c 20 33 35 33 30 33 31 0d> ]
```

**cli.js**
```
events.js:165
      throw err;
      ^

Error: Uncaught, unspecified "error" event. (undefined)
    at EventEmitter.emit (events.js:163:17)
    at /../dbus-test/node_modules/dbus-native/index.js:93:19
    at /../dbus-test/node_modules/dbus-native/lib/handshake.js:104:22
    at /../dbus-test/node_modules/dbus-native/lib/handshake.js:28:14
    at FSReqWrap.oncomplete (fs.js:123:15)
```

Adding an `error` handler I only get an `undefined`, but no real error :(

```js
conn.on('error', function () {
  console.log(arguments);
})
```

I am using node 6.4 and have install dbus via homebrew.

**Comment by nschoe** [comment]
Hi @sebald ,

Can you try to run the `return-types.js` example and query the service on the command line (with `gdbus`, `dbus-send` or equivalent) and see if this works?

Also, you can try `server-signals.js` with `client-signals.js` too, which doesn't require you to use command line. These minimal tests will tell us if there is something wrong with your setup or not :-)

**Comment by sidorares** [comment]
@sebald are you running dbus daemon on mac?

**Comment by sidorares** [comment]
@sebald see related issue #54 - you can install dbus-daemon on osx using `brew install dbus`

**Comment by sebald** [comment]
Wow, thanks for the ultra quick reply!

@sidorares already did that :) I can run `dbus-send` on my terminal. What do you mean by "dbus daemon"?

@nschoe Running `return-types.js` gives the following error:
```
/[...]/node_modules/dbus-native/index.js:25
  if (!busAddress) throw new Error('unknown bus address');
                   ^

Error: unknown bus address
    at createStream (/[...]/node_modules/dbus-native/index.js:25:26)
    at createConnection (/[...]/node_modules/dbus-native/index.js:70:30)
    at Function.module.exports.createClient (/[...]/node_modules/dbus-native/index.js:130:20)
    at Function.module.exports.sessionBus (/[...]/node_modules/dbus-native/index.js:141:25)
    at Object.<anonymous> (/[...]/return-types.js:30:25)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

Running `service-signals.js`:
```
/[...]/node_modules/dbus-native/index.js:25
  if (!busAddress) throw new Error('unknown bus address');
                   ^

Error: unknown bus address
    at createStream (/[...]/node_modules/dbus-native/index.js:25:26)
    at createConnection (/[...]/node_modules/dbus-native/index.js:70:30)
    at Function.module.exports.createClient (/[...]/node_modules/dbus-native/index.js:130:20)
    at Function.module.exports.sessionBus (/[...]/node_modules/dbus-native/index.js:141:25)
    at Object.<anonymous> (/[...]/service-signals.js:24:25)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

I am just learning how the dbus interface works, so I hope I did not ask for too stupid things :-x

**Comment by nschoe** [comment]
No problem, @sebald , but you need to read a little bit about dbus before you can begin.
Basically, in its start, DBus is an IPC mechanism (Inter-Process Communication), it defines a protocol for two processes (think 'programs') to communicate between them (even if they are not written in the same language).

This is DBus as its core. Then there is the dbus daemon, which is a daemon (as its name implies) that use dbus (the IPC library) to talk with several (lots of) applications that use dbus (the lib).

Basically, the dbus daemon keeps track of all the registered clients (which are applications that are connected to the dbus daemon). So rather than `A` talking directly to `B`, `A` talks to `B` through the bus (daemon).

From the error messages you've got, it seems that you don't have a dbus daemon (bus) running, hence the `unknown bus address`. I the bus is launched, you should have an environment variable named `DBUS_SESSION_BUS_ADDRESS`. Check with `env | grep DBUS`.

As @sidorares said, you need to install and run it :-)

**Comment by sidorares** [comment]
@nschoe there is a bit of initial support for connecting clients directly bypassing daemon (my main use case was to try to write a simple implementation of daemon, but there might be other scenarios where this could be useful) - `/examples/p2p` is about this. Basically initial non-message protocol part is skipped and clients are free to exchange messages (up to them how to handle)

**Comment by nschoe** [comment]
@sidorares okay, right. I thought `/examples/p2p` was about something like this, but I wasn't sure.
Thanks for clearing this for me!

**Comment by sebald** [comment]
Thanks a alot @nschoe and @sidorares  I really appreciate your time and patience with me. I read the wikipedia article before I started, because the other program I have to communicate with is written in C++ and this seemed the best way to do it (given the fact that I want to write JS/node).

This really is a good starting point for me and since my issue doesn't have anything to do with your lib, I'll go an close this issue.

Again, thanks a lot! ❤️

**Comment by sebald** [comment]
@sidorares So does this mean it should work w/o a running daemon?

**Comment by sidorares** [comment]
> So does this mean it should work w/o a running daemon?

probably no, depending on what you want to achieve. What's the other service you want to communicate with? Is it your code as well (just in another process) or some service provided by system? In 99% of cases dbus is used to control (or get notified by) some system or desktop service: screensaver, bluez, network manager etc - most of them expose some dbus api - the rest 1% is RPC between processes of one bigger system

**Comment by sebald** [comment]
Since I can not run the other process on my MacBook I wanted to create a mock for it with your library. I basically I want to have `node app 1` <-> `dbus` <-> `node app 2`.

**Comment by sidorares** [comment]
try to install dbus daemon via homebrew ( but using linux+virtualbox might be easier)
You might need to do some extra manual steps (maybe assign session bus address - via `DBUS_SESSION_BUS_ADDRESS` env variable or as client parameter)
