### ISSUE TITLE
How to send null string?

### ISSUE THREAD

**Issue by cruxdyno** [sidorares/node-dbus#135]
Basic question, I hope.  This method takes a string parameter, but I want to send "empty", as they say:
https://developer.gnome.org/NetworkManager/stable/gdbus-org.freedesktop.NetworkManager.Settings.Connection.html#gdbus-method-org-freedesktop-NetworkManager-Settings-Connection.GetSecrets

Error: Serialisation of null value is not supported by d-bus
    at writeSimple (node_modules/dbus-native/lib/marshall.js:102:28)
    at write (node_modules/dbus-native/lib/marshall.js:92:14)

```js
getSystemBus().invoke({
        path: objectPath,
        interface: DBUS_NAME_SETTINGS_CONNECTION,
        member: 'GetSecrets',
        destination: DBUS_NAME_NM,
        signature: 's',
        body: [null]
    }, ...
```
I tried body: [''] but it says: Connection didn't have requested setting ''.  What am I doing wrong?

**Comment by sidorares** [comment]
Yes, dbus protocol does not have NULL type

`body: ['']` looks like the right way to pass empty string

Are you able to use this method from some other client? If so it could be possible to look at dbus traffic and see how it's used

**Comment by cruxdyno** [comment]
Thanks for the quick response!  dbus-send gives me the same error when sending empty string.  I think the documentation might be wrong.  I used dbus-monitor to capture traffic from the network settings app, but it never called GetSecrets.  It's sending secrets to AddAndActivateConnection, so I'm going to use that.

I think it would help to have more examples in the README.  Maybe something like this:

When calling functions on an object, like NetworkManager.AddAndActivateConnection, arguments must be in these formats:
```js
v (variant): ['s', 'river'] or ['b', false]
sv: ['mode', ['s', 'infrastructure']]
a{sa{sv}}: [
                ['connection',[
                    ['id',['s','comcast1234']],
                    ['type',['s', '802-11-wireless']]
                ]]
                , ['802-11-wireless-security',[
                    ['psk',['s','dogsnamebirthday']]
                ]]
            ]
```

To call a method on a subinterface of an object like org.freedesktop.NetworkManager.Device, use as() first:
```js
wirelessDevice = devive.as('org.freedesktop.NetworkManager.Device.Wireless');
wirelessDevice.GetAllAccessPoints(...)
```
