### ISSUE TITLE
No such interface found

### ISSUE THREAD

**Issue by bastimeyer** [sidorares/node-dbus#167]
Hi,
I'm getting the [`No such interface found`](https://github.com/sidorares/node-dbus/blob/f20817f3a426727558a47b911dc1e30e65f51bdd/lib/introspect.js#L22) error after using the latest version from the master branch when I try to get the org.freedesktop.Notifications interface (I haven't tried anything else yet).

The reason for me using the master branch instead of `0.2.3` was the fix of the notation of the octal numbers in fa8835ec9d4bd541b732dbf7a3e7da54d6da16eb. Those had caused issues when minifying the code with `babel-minify`. This commit is working fine and doesn't return the error.

The head of the master branch does not, though, and I think the error is caused by the upgrade of `xml2js` in 8d8b8fe496f0a12e06d82e738ad6876bcf4ec599.

According to the xml2js readme, there has been a change of the default parsing configuration since `0.2.0`, see here: https://github.com/Leonidas-from-XIV/node-xml2js#updating-to-new-version
They've broken the semver versioning scheme by not bumping the major version after this breaking change, so that's probably where this error is coming from after the upgrade from 0.1 to 0.4.

**Comment by sidorares** [comment]
@jrobeson - would you be able to have a look? If that's change in xml parser - downgrade or fix where it is used?

**Comment by jrobeson** [comment]
I think i'm gonna go with a downgrade for now. I have a partial fix, but it's kinda messy in there so I'd rather fix that stuff first.

**Comment by jrobeson** [comment]
PR: https://github.com/sidorares/node-dbus/pull/169

**Comment by jrobeson** [comment]
merged, let us know if it fixes the problem.

**Comment by bastimeyer** [comment]
9b464a1c99ce149dd660e1e88382318d248dff60 fixes the problem. Thanks!
