### ISSUE TITLE
Fields in Interface Description not documented

### ISSUE THREAD

**Issue by athanclark** [sidorares/node-dbus#170]
Hi there,

This library looks really well built, but I can't seem to figure out what the last two fields represent in your return types example: https://github.com/sidorares/node-dbus/blob/master/examples/return-types.js#L72

`['', 's', [], ['hello_sentence']]` - the first two arguments make sense to me; those are the input and output D-Bus type signature strings. But, the last two is where I'm lost - what do they represent? Any help in this regard would be great, I started digging through bus.js and just got lost

**Comment by sidorares** [comment]
they are input signature, output signature, input description, output description - see https://github.com/sidorares/node-dbus/blob/9b464a1c99ce149dd660e1e88382318d248dff60/lib/stdifaces.js#L171-L172 ( implementation of introspection ) and https://github.com/sidorares/node-dbus/blob/9b464a1c99ce149dd660e1e88382318d248dff60/lib/bus.js#L145 ( method call )

**Comment by athanclark** [comment]
Wonderful! Thank you for your quick response. Long live D-Bus!
