### ISSUE TITLE
Fails to call UDisks2 GetManagedObjects.

### ISSUE THREAD

**Issue by mikerussellnz** [sidorares/node-dbus#31]
Using npm version dbus-native@0.0.13

the following fails with:

buffer.js:156
function Buffer(subject, encoding, offset) {
               ^
RangeError: Maximum call stack size exceeded

source code:

var dbus = require('dbus-native');

var bus = dbus.systemBus();
var conn = bus.connection;
conn.message({
    path:'/org/freedesktop/UDisks2',
    destination: 'org.freedesktop.UDisks2',
    'interface': 'org.freedesktop.DBus.ObjectManager',
    member: 'GetManagedObjects',
    type: dbus.messageType.methodCall
});
conn.on('message', function(msg) { console.log(msg); });

**Comment by jrobeson** [comment]
is it fixed now?

**Comment by jrobeson** [comment]
i decided to actually run it, and it does work! :)

**Comment by sidorares** [comment]
I only have linux on virtualbox right now, some functionality is not trivial to test.

**Comment by sidorares** [comment]
oh, great :) thanks for going through issues
