### ISSUE TITLE
Connecting to dbus-daemon on OS X

### ISSUE THREAD

**Issue by JetForMe** [sidorares/node-dbus#54]
I'm trying to connect to dbus-daemon on OS X, but I keep getting this error. I'm confused because I don't want the node client to start a server, I want it to connect to the dbus-daemon, so it shouldn't complain that the address is in use. In this instance, I launched dbus-daemon from the command line and told it to listen on a TCP socket. I get the same response.

    $ node server.js 
    version mismatch between local (0.4.2) and global (undefined) Locomotive module
    Starting podtique config server with content dir: /Users/rmann/Desktop/TAHReencoded
    createStream opts: {}
    Address: tcp:host=localhost,port=64359,guid=9954de09c00a3376525c6a8e5500b6f3
    connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
    connect deprecated limit: Restrict request size at location of read node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
    connect deprecated methodOverride: use method-override npm module instead config/initializers/30_middleware.js:16:20
    events.js:85
          throw er; // Unhandled 'error' event
                ^
    Error: listen EADDRINUSE
        at exports._errnoException (util.js:746:11)
        at Server._listen2 (net.js:1129:14)
        at listen (net.js:1155:10)
        at net.js:1253:9
        at dns.js:85:18
        at process._tickCallback (node.js:355:11)
        at Function.Module.runMain (module.js:503:11)
        at startup (node.js:129:16)
        at node.js:814:3

**Comment by sidorares** [comment]
Can you describe the steps to install/configure daemon? Most osx users don't have dbus launched by default and your question might be very configuration specific.

The error you see is from some server not being able to bind to a port, which is probably not in dbus client's code. Can you try to manually connect to tcp: 64359 ? Just by doing `telnet 127.0.0.1 64359`?

**Comment by JetForMe** [comment]
Augh, I'm so sorry. The error was not due to node-dbus, but something else entirely. node-dbus doesn't seem to automatically find it, but if I configure the right address in the env variable, it appears to connect. For completeness, here's how you set up dbus on OS X:

Yes. Dbus is installed on OS X via [brew](http://brew.sh/):

    $ brew install dbus
    ==> Downloading https://homebrew.bintray.com/bottles/d-bus-1.8.14.yosemite.bottle.tar.gz
    Already downloaded: /Library/Caches/Homebrew/d-bus-1.8.14.yosemite.bottle.tar.gz
    ==> Pouring d-bus-1.8.14.yosemite.bottle.tar.gz
    ==> Caveats
    To have launchd start d-bus at login:
        ln -sfv /usr/local/opt/d-bus/*.plist ~/Library/LaunchAgents
    Then to load d-bus now:
        launchctl load ~/Library/LaunchAgents/org.freedesktop.dbus-session.plist

Then execute the additional commands under "Caveats" above. At this point, there is no dbus-daemon process running. Once launchd is set up, it listens on a Unix Domain socket. The first connection to that socket launches dbus-daemon --session --nofork.

**Comment by sidorares** [comment]
No problems! It interesting to see how it's used on osx

**Comment by JetForMe** [comment]
Yeah, I had my server running in a different terminal window that was minimized. That's why I got the EADDRINUSE errors; not from dbus, but from my server trying to listen. So dumb.
