### ISSUE TITLE
Trouble finding my service

### ISSUE THREAD

**Issue by JetForMe** [sidorares/node-dbus#55]
I realize this problem might be due to my lack of familiarity with dbus, but I'm running into this:

    error: The name com.latencyzero.podtique was not provided by any .service files

Here's my code:

    var sessionBus = dbus.sessionBus();
    var service = sessionBus.getService('com.latencyzero.podtique');
    service.getInterface('/com/latencyzero/podtique',
                            'com.latencyzero.podtique',
                            function(err, notifications)
                            {
                                if (err)
                                {
                                    console.log("dbus error: " + err);
                                }
                                else
                                {
                                    notifications.on('RadioStatus', function()
                                    {
                                        console.log('RadioStatus', arguments);
                                    });
                                }
                            });

I don't have any .service files. My C++ code seems to be able to construct and send a message without error like this:

    const char* kDestination                =   "com.latencyzero.podtique";
    const char* kPath                       =   "/com/latencyzero/podtique";
    const char* kInterface                  =   "com.latencyzero.podtique";
    const char* kMethodRadioStatus          =   "RadioStatus";
    
    DBus::Message msg(kDestination,
                        kPath,
                        kInterface,
                        kMethodRadioStatus);
    msg.setNoReply(true);
    msg.append(inOn);
    
    bool success = send(msg);
    if (!success)
    {
        LogDebug("Unable to send message");
        return false;
    }
    
    return true;

(the C++ code is just a wrapper around the standard libdbus API dbus_message_new_method_call() and dbus_message_append_args() and dbus_connection_send().

**Comment by sidorares** [comment]
this usually means that 'com.latencyzero.podtique' is not started and dbus daemon need to look at list of .services to see if it's configured to be started on first message. Could you try to invoke `org.freedesktop.DBus.ListNames` method? There is a [helper](https://github.com/sidorares/node-dbus/blob/master/lib/bus.js#L324) for it so you can call `sessionBus.listNames(callback)`. Also same for ListActivatableNames - see http://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-messages for documentation

**Comment by JetForMe** [comment]
I called listNames, and my function is called back, but I don't know how to get at the names. I tried putting in a single argument but it was undefined. Where is the callback's signature documented?

```
var sessionBus = dbus.sessionBus();
sessionBus.listNames(function()
{
    console.log("listNames");
});

$ node server.js 
version mismatch between local (0.4.2) and global (undefined) Locomotive module
Starting podtique config server with content dir: /Users/rmann/Desktop/TAHReencoded
createStream opts: {}
Address: unix:path=/private/tmp/com.apple.launchd.IcssYRtjVk/unix_domain_listener
connect deprecated multipart: use parser (multiparty, busboy, formidable) npm module instead node_modules/express/node_modules/connect/lib/middleware/bodyParser.js:56:20
connect deprecated limit: Restrict request size at location of read node_modules/express/node_modules/connect/lib/middleware/multipart.js:86:15
connect deprecated methodOverride: use method-override npm module instead config/initializers/30_middleware.js:16:20
HTTP server listening on 0.0.0.0:3000
socket init
listNames
dbus error: The name com.latencyzero.podtique was not provided by any .service files
```

**Comment by JetForMe** [comment]
Oh, I found "arguments":

```
listNames: {"0":null,"1":["org.freedesktop.DBus",":1.0",":1.10"]}
```

**Comment by sidorares** [comment]
it follows usual node CPS convention - first argument is error (`null` if no error)

**Comment by sidorares** [comment]
so this means you have only one service on your bus - standard `org.freedesktop.DBus` implemented by daemon. Why would you expect 'com.latencyzero.podtique' in that list? Have you started it explicitly on the same machine?

**Comment by JetForMe** [comment]
Again, I don't quite understand how dbus works. I thought if one client sent a message, then another client would receive it. I didn't know I had to somehow define the services. The C code doesn't report any errors when trying to send the message. I don't yet know how to configure dbus-daemon to expose that service.

**Comment by JetForMe** [comment]
The .service file examples I find online all seem to be about exec-ing some program; I don't want to do that. The two processes that need to communicate with each other are both started independently at boot (my C++ program, and my node.js server).

**Comment by sidorares** [comment]
Client send a message to a bus with service address as part of message ( "com.latencyzero.podtique" in your case ). When the client connects to bus, it has to send "Hello" message and gets automatically assigned name initially (something like ":123") and can later ask bus to change name.

When bus receive a message, it looks at service name in the message, checks if there is another connection with that name assigned and routes it to it. In your case you have one connection to bus ( your client ) and no other service running

**Comment by JetForMe** [comment]
For this particular message, my C++ program will send it, and I want the node.js server to receive it. That implies that dbus-native needs to create the service, right? I don't know what piece I'm missing.

**Comment by sidorares** [comment]
Have you started your C++ program ? ListNames response suggests that it's not connected to a bus. dbus daemon does not persist messages, it's not message queue. You have to have both clients running to be able to exchange messages

**Comment by JetForMe** [comment]
Yes, it's running. It connects to the bus and sends that message above on startup, then any time I change the RadioStatus.

**Comment by JetForMe** [comment]
FYI, I based my C++ code off of this example: http://maemo.org/development/training/maemo_platform_development_content/plain_html/node10/

**Comment by sidorares** [comment]
if it is running you should be able to see it in ListNames

Try to start another dbus-native client ( while first one is still running ) and call listNames fro it - you should be able to see first client name in response

**Comment by JetForMe** [comment]
That's how I've been trying to do it all along; I set up launchd (one time), then I launch my C++ process, which when it tries to connect to the session bus, causes dbus-daemon to be launched. My C++ process doesn't do anything else other than send the method calls (and forget them).

I didn't really want to have to define a bunch of object state to put into dbus; I just want asynchronous messages (sometimes with reply) to be sent between them, in both directions. I thought dbus-daemon allowed for that, but that doesn't seem to be the case.

**Comment by JetForMe** [comment]
I've finally figured out enough about dbus to get this to work. I had to call dbus_request_name() in order to advertise my destination (I also had to handle dispatching dbus events myself). Now I seem to be able to pass and receive messages in both directions. Thank you for all your help!

**Comment by sidorares** [comment]
Great!
