### ISSUE TITLE
How to stop listening to signals

### ISSUE THREAD

**Issue by nisargjhaveri** [sidorares/node-dbus#60]
I am binding an event handler as followed
```javascript
var screenSaver;
sessionBus.getService('org.gnome.ScreenSaver').getInterface(
    '/org/gnome/ScreenSaver',
    'org.gnome.ScreenSaver',
    function(err, _screenSaver) {
        screenSaver = _screenSaver;

        screenSaver.on('ActiveChanged', screenSaverActiveChange);
    }
);
```

Now after some time I want to unbind the `screenSaverActiveChange` event handler, so I tried,

```javascript
screenSaver.removeListener('ActiveChanged', screenSaverActiveChange);
```

But it says,
> removeListener not implemented for dbus signals

Now, what is the correct way to unbind this event handler? Is there any other way I can implement the similar thing?

**Comment by sidorares** [comment]
yes, it's currently not implemented. You can manually call `sessionBus.removeMatch(rule)` - see how to construct rules here: http://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-routing-match-rules

**Comment by sidorares** [comment]
And feel free to send PR if you add proper support for `interface.removeListener` :)

**Comment by jazzpi** [comment]
Could you provide an example for `bus.removeMatch`?

I tried this:

```javascript
> bus.signals._events
{ '{"path":"/org/mpris/MediaPlayer2","interface":"org.freedesktop.DBus.Properties"}': [Function],
  '{"path":"/org/mpris/MediaPlayer2","interface":"org.freedesktop.DBus.Properties","member":"PropertiesChanged"}': [ [Function], [Function] ] }
> bus.removeMatch('path=\'/org/mpris/MediaPlayer2\',interface=\'org.freedesktop.DBus.Properties\',member=\'PropertiesChanged\'', function(err, data){console.log(err, data)})
undefined
> undefined undefined
> bus.signals._events
{ '{"path":"/org/mpris/MediaPlayer2","interface":"org.freedesktop.DBus.Properties"}': [Function],
  '{"path":"/org/mpris/MediaPlayer2","interface":"org.freedesktop.DBus.Properties","member":"PropertiesChanged"}': [ [Function], [Function] ] }
```

**Comment by sidorares** [comment]
What you tried looks ok to me. Do you still get signals back after `removeMatch`?
Note that `removeMatch` only changes your subscription on the bus, you still need to call `removeListener` to remove EventEmitter handler from associated signal event ( but first even part should be enough as it would prevent signal messages from being sent to your client )

note that to implement this properly we probably need to refcount signals as multiple path in the code can subscribe ( = AddMatch ) and only last `removeListener` need to cause `RemoveMatch` to be invoked

**Comment by sidorares** [comment]
also see #26

**Comment by jazzpi** [comment]
Yes, I still receive signals (I bound a simple logging function to the Event, and I still get the output).

I never used any EventEmitter handlers, so what would I need to do to remove it?

**Comment by sidorares** [comment]
`bus.signals` is EventEmitter ( https://github.com/sidorares/node-dbus/blob/master/lib/bus.js#L16 )
but handler is not assigned directly ( see https://github.com/sidorares/node-dbus/blob/master/lib/introspect.js#L37 )

The fact that you receive signals means match rule is probably not correct. Can you print one used by `AddMatch`? Add `console.log(match)` before https://github.com/sidorares/node-dbus/blob/master/lib/introspect.js#L32

**Comment by jazzpi** [comment]
Okay, this actually worked:

```javascript
> dbus = require('dbus-native')
{ [Function: createConnection]
  createClient: [Function],
  [...]
  createServer: [Function] }
> bus = dbus.sessionBus()
{ connection: 
   { domain: 
      { domain: null,
  [...]
  nameHasOwner: [Function] }
> var interface
undefined
> bus.getService('org.mpris.MediaPlayer2.spotify').getInterface('/org/mpris/MediaPlayer2', 'org.freedesktop.DBus.Properties', function(err, _interface){interface = _interface})
undefined
> function testLog(a, b, c) {console.log(a); console.log(b); console.log(c)}
undefined
> interface.on('PropertiesChanged', testLog)
type='signal',member='PropertiesChanged'
undefined
> org.mpris.MediaPlayer2.Player
[ [ 'Metadata', [ [Object], [Object] ] ] ]
[]

undefined
> bus.signals._events
{ '{"path":"/org/mpris/MediaPlayer2","interface":"org.freedesktop.DBus.Properties","member":"PropertiesChanged"}': [Function] }
> bus.removeMatch("path='/org/mpris/MediaPlayer2',interface='org.freedesktop.DBus.Properties',member='PropertiesChanged'")
undefined
> org.mpris.MediaPlayer2.Player
[ [ 'Metadata', [ [Object], [Object] ] ] ]
[]
> bus.signals._events
{ '{"path":"/org/mpris/MediaPlayer2","interface":"org.freedesktop.DBus.Properties","member":"PropertiesChanged"}': [Function] }
> bus.removeMatch("type='signal',member='PropertiesChanged'")
undefined
> bus.signals._events
{ '{"path":"/org/mpris/MediaPlayer2","interface":"org.freedesktop.DBus.Properties","member":"PropertiesChanged"}': [Function] }
> 
```

I don't get the logging output anymore now. I think I was confused by the `bus.signals._events` containing something different that seemed to match the binding.

**Comment by nisargjhaveri** [comment]
On doing `removeListener` on `bus.signals`, I am able to get `bus.signals._events` empty after changing a bit in `introspect.js`.

My problem now is, do I still need to do `RemoveMatch` after  `bus.signals._events` is empty for some signal or is it taken care of?

**Comment by jazzpi** [comment]
I think I now understand how this works - `interface.on` is a binding for `bus.addMatch` and `bus.signals.addListener`.

It adds a match for the signal you specified (e.g. `ActiveChanged`) so that every time an `ActiveChanged` DBus signal is sent, it checks the listeners specified in `bus.signals._events` if it matches any of them.

If it finds a listener that matches, it executes that (e.g. the path is `/org/gnome/ScreenSaver`, the interface is `org.gnome.ScreenSaver` and the signal sent is `ActiveChanged`).

So when you remove the listener, you still have the match so it will still check your listeners everytime an `ActiveChanged` signal is sent.
If you remove the match, you still have the listener, so when you do `interface.on` again, you'll have two listeners doing the same.

**Comment by nisargjhaveri** [comment]
Hmm. looking into it. Will send a PR soon, if everything goes fine!

**Comment by nisargjhaveri** [comment]
See #63.

**Comment by sidorares** [comment]
@jazzpi `bus.addMatch` sends a message to a dbus daemon "hey, whenever you have 'ActiveChanged' signal message, please send it to me as well". bus.signals serves as a client side router: it's a node EventEmitter, and event name here is signal + object path + interface ( so that same signals from different objects / interfaces are distinguished )

@nisargjhaveri as I mentioned, signals needs to be refcounted client side. Imagine that in two parts of your code working with one single dbus connection you have `on('signal1', handlerOne)` and `on('signal1', handlerTwo)`. RemoveMatch needs to be sent only when _both_ listeners are removed on client, otherwise when you remove handlerOne handlerTwo stops getting messages

**Comment by sidorares** [comment]
also it looks like match rule is very broad - it's for any signal matching a name ( regardless of object / interface ) and additional filtering is performed at client. Need to add object and interface to a match rule

**Comment by nisargjhaveri** [comment]
I think, It takes care of interface at https://github.com/sidorares/node-dbus/blob/master/lib/introspect.js#L37. See the `signalFullName` argument.

Also, can you look at the PR. I think I have taken care of the removeMatch problem you mentioned.

**Comment by sidorares** [comment]
only client side- see match rule printed in https://github.com/sidorares/node-dbus/issues/60#issuecomment-87395532 is `type='signal',member='PropertiesChanged'` and does not include service name / object path or interface name

**Comment by sidorares** [comment]
@nisargjhaveri I think both problems still exist: 1) you can accidentally remove match for all signals with that name while you intended to unsubscribe only from one and 2) if you have multiple listeners for one signal RemoveMatch needs to be sent when last listener is removed

**Comment by nisargjhaveri** [comment]
Oh wait! It just doesn't care which interface it is when addMatch or removeMatch is called. This means that if some other interface has member with same name, it is also matched. Am I right?

In that case, Shouldn't we should change addMatch and reomoveMatch also to account for object path and interface name?

Also, is there any way to get all handlers listening to a single match?

**Comment by sidorares** [comment]
yes. Documentation on how to construct match rule is here - http://dbus.freedesktop.org/doc/dbus-specification.html#message-bus-routing-match-rules

I would suggest to use [dbus-monitor](http://dbus.freedesktop.org/doc/dbus-monitor.1.html) as a tool to explore & verify match rules

**Comment by nisargjhaveri** [comment]
I've updated the PR. Can you look at it?

**Comment by sidorares** [comment]
Thanks! Looks good to me! I'll try to test match rules.
Some style nitpicks: use `[]` instead of `new Array()` and `arr.length = 0` to clear array instead of `arr = new Array()`; 

https://coderwall.com/p/h4xm0w/why-never-use-new-array-in-javascript
http://stackoverflow.com/questions/4804235/difference-between-array-length-0-and-array
http://www.2ality.com/2012/12/clear-array.html

**Comment by sidorares** [comment]
@nisargjhaveri moving discussion to pr thread
