### ISSUE TITLE
How does node-dbus handle 64 bit numbers?

### ISSUE THREAD

**Issue by lucidguppy** [sidorares/node-dbus#61]
Since javascript can't really handle 64 bit numbers - wondered how node-dbus handled them.

Should the limit be 53 bits?  I was thinking node-dbus should just reject 64 bit datatypes.

http://stackoverflow.com/a/24037917/49945

**Comment by sidorares** [comment]
Currently it just does JS math so it's not accurate. Yes, need to add run time check for range and/or use big number library  - https://github.com/sidorares/node-dbus/blob/master/lib/dbuffer.js#L191

I use bn.js in node-mysql2: https://github.com/sidorares/node-mysql2/blob/master/lib/packets/packet.js#L124-L134
