### ISSUE TITLE
Are square brackets valid in signatures? 

### ISSUE THREAD

**Issue by lucidguppy** [sidorares/node-dbus#64]
In the marshall/unmarshall test I see one line that contains brackets.  Is that a valid signature? Reason I'm asking was my validation for signatures was raising an error on this line.

     ['g', ['xxxtt[t]s{u}uuiibb']]

Should it be

     ['g', ['xxxtt(t)s{u}uuiibb']]

I couldn't find square brackets in the dbus spec.

**Comment by sidorares** [comment]
No - http://dbus.freedesktop.org/doc/dbus-specification.html#idp94392448

Also I'll need to double check if we handle 'r' as alias to structire and 'e' as alias to dict entry

**Comment by sidorares** [comment]
ok, it's not actually parsed, it's just a string saved as 'g' ( but I'll probably add validation to 'g' type )

**Comment by sidorares** [comment]
added validation
