### ISSUE TITLE
align.js - ok to use Buffer without requiring?

### ISSUE THREAD

**Issue by lucidguppy** [sidorares/node-dbus#69]
I noticed in my changes when I split out align.js I didn't require Buffer - is that ok?  I didn't catch it because the tests passed.

**Comment by sidorares** [comment]
I think it's ok since node 10 - I'll check build matrix. If we can support node 0.8 and it's not automatically in scope I'll add require

**Comment by sidorares** [comment]
https://nodejs.org/api/buffer.html

> The Buffer class is a global, making it very rare that one would need to ever require('buffer').

**Comment by jrobeson** [comment]
this can be closed then.
