### ISSUE TITLE
Monitoring NetworkManager 1.0

### ISSUE THREAD

**Issue by linux4kix** [sidorares/node-dbus#71]
I am trying to switch from the libdbus based node-dbus over to dbus-native and am having some problems with getting signals from NetworManager.  If I run dbus-monitor with the parameters in this script I see all the messages come across.  My script runs and connects to the system bus but I get no signals emitted.

```js
var bus = require('dbus-native').systemBus();
var signame = 'StateChanged';
bus.addMatch('type=\'signal\',member=\'' + signame + '\'',
             function(err, value) {
                 if (err) throw new Error(err);                                      
});                                                        
var signalFullName = bus.mangle('/org/freedesktop/NetworkManager',
                                'org.freedesktop.NetworkManager',
                                signame);

bus.signals.on(signalFullName, function(messageBody) {                  
    console.log(messageBody);
});
```

**Comment by sidorares** [comment]
try to log all incoming messages with
```js
bus.connection.on('message', function(msg) {
   console.log(msg);
});
```

**Comment by linux4kix** [comment]
Nothing from NetworkManager.   I get the initialization messages from
org.freedesktop.DBus but after unplugging and plugging in an ethernet cable
I see nothing.

{ serial: 1,
  destination: ':1.98',
  replySerial: 1,
  signature: 's',
  sender: 'org.freedesktop.DBus',
  type: 2,
  flags: 1,
  body: [ ':1.98' ] }
{ serial: 2,
  path: '/org/freedesktop/DBus',
  interface: 'org.freedesktop.DBus',
  member: 'NameAcquired',
  destination: ':1.98',
  signature: 's',
  sender: 'org.freedesktop.DBus',
  type: 4,
  flags: 1,
  body: [ ':1.98' ] }

**Comment by sidorares** [comment]
Can you put your dbus-monitor command here, I'll try to reproduce

**Comment by linux4kix** [comment]
Sure. Thanks for taking a look at this.

dbus-monitor --system
"type='signal',sender='org.freedesktop.NetworkManager',interface='org.freedesktop.NetworkManager',member='StateChanged'"

Then unplugged the network cable, or turning off your wifi should cause a
bunch of uint32's to be returned.

**Comment by yangpeng1973** [comment]
I have encountered the same problem.

**Comment by sidorares** [comment]
@linux4kix your code works for me

Note that bus.signals is not intended for external usage, it's private to code implementing signal routing

also `dbus-monitor` adds "eavesdrop=true", but it does not make difference in my setup

You can watch what messages dbus-monitor is sending by using https://github.com/sidorares/node-dbus/blob/master/bin/dbus-dissect.js script:
Start `node dbus-dissect.js --system` in one window and then ` DBUS_SESSION_BUS_ADDRESS=tcp:host=127.0.0.1,port=3334 dbus-monitor "type='signal',senr='org.freedesktop.NetworkManager',interface='org.freedesktop.NetworkManager',member='StateChanged'"` in another

**Comment by linux4kix** [comment]
Thanks for following up.  For now I have changed my code to use the getInterface method to provide an interface I can listen to for changes.  That is working for me.

**Comment by sidorares** [comment]
there is also a script to generate client from introspection ahead of time instead of doing it dynamically, check out https://github.com/sidorares/node-dbus/blob/master/bin/dbus2js.js

**Comment by linux4kix** [comment]
Yes I have tested that and even adapted it to xml2js v2 and greater.  Those
bindings are what were failing and originally started this discussions.
Doing it statically would help because right now the instantiation is quite
slow and lends itself to race conditions on initialization that I have to
code around.  Basically the addListener function that is generated was the
basis for the original test code I posted.

**Comment by linux4kix** [comment]
Actually I have finally realized what the problem is.  When trying to setup
the addMatch rule for the listener we are racing and hitting this check.
 if(!self.name) return callback(null, null);  This is why the check for err
is failing we are bailing out but not returning an error!  Because of this
addMatch is never sent over the bus and the reason I don't get any signals.

It seems we should be emitting a ready signal once the initial 'Hello'
message returns.

**Comment by sidorares** [comment]
what callback are you talking about?

**Comment by linux4kix** [comment]
The return callback in this block.  Why is this not returning an error?

    // bus meta functions
    this.addMatch = function(match, callback) {
        if(!self.name) return callback(null, null);
        this.invokeDbus({ 'member': 'AddMatch', signature: 's', body:
[match] }, callback);
    };

**Comment by linux4kix** [comment]
So for testing.  I have added a patch here.

diff --git a/lib/bus.js b/lib/bus.js
index cc8f482..00797b5 100644
--- a/lib/bus.js
+++ b/lib/bus.js
@@ -241,6 +241,7 @@ module.exports = function bus(conn, opts) {
         this.invokeDbus({ member: 'Hello' }, function(err, name) {
             if (err) throw new Error(err);
             self.name = name;
+            self.signals.emit('ready');
         });
     } else {
         self.name = null;


Then in my test code waiting for that signal before setting up my signal
handlers.

var bus = require('../index.js').systemBus();
var interface = require('./nm.js');

nm = new interface['org.freedesktop.NetworkManager'](bus);

bus.signals.on('ready', function() {
    nm.on('PropertiesChanged', function(properties) {
        console.log('PropertiesChanged', properties);
    });
});

That allows me to catch the signals and get back the structure.

libphy: 2188000.ethernet:00 - Link is Down
PropertiesChanged [ [ 'State', [ [Object], [Object] ] ],
  [ 'PrimaryConnection', [ [Object], [Object] ] ],
  [ 'ActiveConnections', [ [Object], [Object] ] ],
  [ 'Connectivity', [ [Object], [Object] ] ] ]

**Comment by sidorares** [comment]
hm, not sure. Looks like a bug

**Comment by sidorares** [comment]
there is "connect" event at the end of initial handshake and response to "Hello" message - https://github.com/sidorares/node-dbus/blob/master/index.js#L96

**Comment by sidorares** [comment]
actually, it's emitted before 'Hello'
Hello is sent from here - https://github.com/sidorares/node-dbus/blob/master/index.js#L96

**Comment by sidorares** [comment]
ok, the code is related to "direct" mode - see https://github.com/sidorares/node-dbus/commit/90593b751d1d4168fe636b7799c3ccc2ca8fc514 and #47

**Comment by linux4kix** [comment]
Yep that is exactly it.  Any ideas what the best fix is?
