### ISSUE TITLE
Invalid struct data with 'av' marshalling

### ISSUE THREAD

**Issue by FrankUrbainsky** [sidorares/node-dbus#73]
When i try to update my lan connection via dbus call to network manager i get an invalid struct data error.
My guess would be that i somehow use the 'av' part for address-data incorrectly.
In the network-manager connection settings specification ( https://developer.gnome.org/NetworkManager/stable/ref-settings.html ) address-data is an 'array of vardict' . I'm not even sure if i translated that correctly into an 'a{sv}' here.

Here is some example code for my problem:

```js
    var dbus = require('dbus-native');
    var _bus = dbus.systemBus();

    updateConnection();

    /**
     * updates an existing network connection
     */
    function updateConnection() {

      connection = [
        ["connection",[
          ["id",["s","Ethernet connection 1"]],
          ["uuid",["s","e341b3bc-3ddd-4fd3-bddd-8b71162f5c33"]],
          ["type",["s","802-3-ethernet"]]
        ]],
        ["ipv4",[
          ["address-data",["av",
            [
              ["sv",[["address"],["s","192.168.1.1"]]],
              ["sv",[["prefix"],["u",24]]]
            ]
          ]],
          ["method",["s","manual"]]
        ]],
        ["802-3-ethernet",[
          ["duplex",["s","full"]]
        ]],
        ["ipv6",[
          ["method",["s","auto"]]
        ]]
      ]
      
      path = '/org/freedesktop/NetworkManager/Settings/18';
      
      _bus.getService('org.freedesktop.NetworkManager').getInterface(
        path,
        'org.freedesktop.NetworkManager.Settings.Connection', function(err, Connection) {
          if (err){
            console.log(err);
          }

          Connection.Update(connection, function(err,one){
            console.log(err,one);
          });
        }
      );
    }
```

**Comment by sidorares** [comment]
currently when signature is more than one character length you need to pass data as a struct ( even if parsed signature at this level only contains one element ) See code here - https://github.com/sidorares/node-dbus/blob/master/lib/marshall.js#L80-L88

I don't like this and likely to change it to be more consistent ( probably "always struct", + helper function `dbus.variant()` + allow to pass objects for `a{sv}` types )

In your example "av" variant data has to be structure with array as first element:

```
 ["address-data",["av",
          [ // added
            [
              ["sv",[["address"],["s","192.168.1.1"]]],
              ["sv",[["prefix"],["u",24]]]
            ]
          ] // added. I know, it's ugly
          ]]
```

**Comment by FrankUrbainsky** [comment]
Thanks for your awesomely fast reply!
I stopped trying to use the new address-data variant as your solution just did throw another error. 
I got it working with the old addresses variant tho: 

["ipv4",[
          ["addresses",["a{au}",
          [ // added
            [[ // added even more :)
              ["au",
                [
                  [ipToInt("192.168.1.1"),24,0]
                ]
              ]
            ]] // added.
          ] // added. I know, it's ugly
          ]],
          ["method",["s","manual"]]
        ]]

Perhaps that is some help for other people trying to work the network-manager.

**Comment by sidorares** [comment]
great! If you feel like you know how to improve this library - PRs - are always welcome :)
