### ISSUE TITLE
Error when get a service from org.freedesktop.PolicyKit1

### ISSUE THREAD

**Issue by wpp2014** [sidorares/node-dbus#74]
When I use dbus-native to get a service from org.freedesktop.PolicyKit1,but I get failed.
Here is my code:

```js
var dbus = require('dbus-native');

action_id = 'org.freedesktop.policykit.exec';
details = {};
flags = 1;
cancellation = '';

var sessionBus = dbus.sessionBus();
sessionBus.getService('org.freedesktop.PolicyKit1').getInterface(
    '/org/freedesktop/PolicyKit1/Authority',
    'org.freedesktop.PolicyKit1.Authority', function(err, notifications) {
        if(err){
                console.log('err'+err);
        }
        console.log(JSON.stringify(notifications));
         notifications.CheckAuthorization(('unix-process', {'pid':process.getpid, 'start-time':0}), action_id, details, flags, cancellation_id, function(err, id) {
        console.log('wpp');
    });
});
```

And here is my error:

![screenshot from 2015-04-15 11 46 56](https://cloud.githubusercontent.com/assets/7447933/7151966/272a93c8-e365-11e4-84e3-e0d0d59f55a8.png)

**Comment by sidorares** [comment]
you do not seem to have policyKit running - you can see all available session services with this command:
```
dbus-send --session           \
  --dest=org.freedesktop.DBus \
  --type=method_call          \
  --print-reply               \
  /org/freedesktop/DBus       \
  org.freedesktop.DBus.ListNames
```

Note that you checking error result, but don't stop if there is an error:

```js
var sessionBus = dbus.sessionBus();
sessionBus.getService('org.freedesktop.PolicyKit1').getInterface(
    '/org/freedesktop/PolicyKit1/Authority',
    'org.freedesktop.PolicyKit1.Authority', function(err, notifications) {
        if(err) {
                console.log('err'+err);
                // !!! error here, you can't use notifications - "The name org.freedesktop.PolicyKit1 was not provided by any .service files"
                return;
        }
        console.log(JSON.stringify(notifications));
         notifications.CheckAuthorization(('unix-process', {'pid':process.getpid, 'start-time':0}), action_id, details, flags, cancellation_id, function(err, id) {
        console.log('wpp');
    });
});
```

**Comment by wpp2014** [comment]
When I use a python to get the service, I succeed,but got error when I do the same thing in dbus-native.
I use dbus.get_object and dbus.Interface in python ,and I get the service.
Is there something different between python-dbus and your dbus-native?
Here is my python code:
import dbus

bus = dbus.SystemBus()
proxy = bus.get_object('org.freedesktop.PolicyKit1', '/org/freedesktop/PolicyKit1/Authority')
authority = dbus.Interface(proxy, dbus_interface='org.freedesktop.PolicyKit1.Authority')

system_bus_name = bus.get_unique_name()

subject = ('system-bus-name', {'name' : system_bus_name})
action_id = 'org.freedesktop.policykit.exec'
details = {}
flags = 1            # AllowUserInteraction flag
cancellation_id = '' # No cancellation id

result = authority.CheckAuthorization(subject, action_id, details, flags, cancellation_id)

print 'result',result
print 'system_bus_name',system_bus_name

I run the code in Linux-Mint is ok.
Can you give me some advities?

**Comment by wpp2014** [comment]
Oh, I had result this problem and I meet I new problem,It's a systembus not a sessionbus.
How can I get the correct data structure to send to dbus?
![screenshot from 2015-04-15 13 02 24](https://cloud.githubusercontent.com/assets/7447933/7152504/ae7f4cba-e36f-11e4-9ea7-0e01c243c084.png)
Here is the method I want use.
And here is the data structure in my python code.
What can I do if I want use it in your dbus-native? It seems different between dbus-native and python-dbus.
![screenshot from 2015-04-15 13 04 42](https://cloud.githubusercontent.com/assets/7447933/7152517/fe46dace-e36f-11e4-819a-05c9da3d5357.png)
![screenshot from 2015-04-15 13 05 02](https://cloud.githubusercontent.com/assets/7447933/7152525/0aa2f564-e370-11e4-99cc-1dc54c7312ee.png)

**Comment by sidorares** [comment]
try to run `node dbus2js.js --system --service org.freedesktop.PolicyKit1 --path /org/freedesktop/PolicyKit1/Authority` in node_modules/dbus-native/bin folder ( you might need to do `npm install optimist` before ) I think I don't have PolicyKit in my ubuntu 14.04, trying to install it manually

**Comment by sidorares** [comment]
it should generate something like this: https://gist.github.com/sidorares/49923066871f7042b8b9

**Comment by sidorares** [comment]
CheckAuthorization  signature is `(sa{sv})sa{ss}us`,
sa{sv} - subject
s - action_id
a{ss} - details
u - flags
s - cancellation_id

```js
var subject = [
    'unix-process', // s
    [ // a
       ['pid', [ 'u', process.getpid ] ],  // sv, v is of u type
       ['start-time', ['u', 0] ] // sv
    ] 
];
action_id = 'org.freedesktop.policykit.exec'; // s
details = []; // empty a{ss} array. If you want to add values it would be [ [ 'foo', 'bar'], [ 'baz', 'test' ] ]
flags = 1; // u
cancellation_is = ''; // s
```

look at types documentation I started to write down in #52

**Comment by wpp2014** [comment]
I used your method, but I met another mistake ：
![screenshot from 2015-04-15 14 00 11](https://cloud.githubusercontent.com/assets/7447933/7152989/0eb6b9b2-e378-11e4-88ea-55866e9d15fb.png)

**Comment by sidorares** [comment]
check that you spelled variable names correctly ( or just `console.log()` all the arguments to  CheckAuthorization )

**Comment by wpp2014** [comment]
Thank you!

**Comment by sidorares** [comment]
did that work? :)

**Comment by sidorares** [comment]
post a gist to your script, I'll try it in my vm

**Comment by wpp2014** [comment]
I want to elevate privileges to the current process .Pop up a dialog and enter the password，then the process run as root
![screenshot from 2015-04-15 14 46 04](https://cloud.githubusercontent.com/assets/7447933/7153492/f20682fa-e37e-11e4-9eb4-22c81ff6057e.png)

this is my script but the specific function is not implemented ：

var dbus = require('dbus-native');
var date = new Date();

action_id = 'org.freedesktop.policykit.exec';
details = [];
flags = 1;
cancellation_id = '';

var subject = [
    'unix-process', // s
    [ // a
       ['pid', [ 'u', process.pid ] ],  // sv, v is of u type
       ['start-time', ['u', date.getTime()] ] // sv
    ] 
];

var systemBus = dbus.systemBus();

systemBus.getService('org.freedesktop.PolicyKit1').getInterface(
    '/org/freedesktop/PolicyKit1/Authority',
    'org.freedesktop.PolicyKit1.Authority', function(err, notifications) {
   	if(err){
		console.log('err'+err);
		return;
	}
	notifications.CheckAuthorization(subject, action_id, details, flags, cancellation_id);
});

**Comment by sidorares** [comment]
can you post working python script as well?
I replaced `date.getTime()` with `parseInt(date.getTime()/1000)` in your code so it fits into 32 bit int ( I assume it is in seconds, not milliseconds ) but see no dialog ( and no error )

**Comment by wpp2014** [comment]
import dbus
import time
import os

bus = dbus.SystemBus()
proxy = bus.get_object('org.freedesktop.PolicyKit1', '/org/freedesktop/PolicyKit1/Authority')
authority = dbus.Interface(proxy, dbus_interface='org.freedesktop.PolicyKit1.Authority')

system_bus_name = bus.get_unique_name()

subject = ('unix-process', {'pid' : dbus.UInt32(os.getpid()), 'start-time': dbus.UInt64(time.time())})
action_id = 'org.freedesktop.policykit.exec'
details = {}
flags = 1            # AllowUserInteraction flag
cancellation_id = '' # No cancellation id

result = authority.CheckAuthorization(subject, action_id, details, flags, cancellation_id)

print 'result',result
print 'system_bus_name',system_bus_name

**Comment by sidorares** [comment]
got it working by making time a 't' type ( 64 bit unsigned int ). Unfortunately 64 bit ints are not fully supported, you'll have to comment out https://github.com/sidorares/node-dbus/blob/master/lib/marshallers.js#L167 in your copy


```js
var dbus = require('dbus-native');
var date = new Date();

action_id = 'org.freedesktop.policykit.exec';
details = [];
flags = 1;
cancellation_id = '';

var subject = [
    'unix-process', // s
    [ // a
       ['pid', [ 'u', process.pid ] ],  // sv, v is of u type
       ['start-time', ['t', parseInt(date.getTime()/1000)] ] // sv
    ] 
];

var systemBus = dbus.systemBus();

systemBus.getService('org.freedesktop.PolicyKit1').getInterface(
    '/org/freedesktop/PolicyKit1/Authority',
    'org.freedesktop.PolicyKit1.Authority', function(err, notifications) {
    if(err){
        console.log('err'+err);
        return;
    }
    notifications.CheckAuthorization(subject, action_id, details, flags, cancellation_id, function(err, result) {
      if(err){
          console.log('err'+err);
          return;
      }
      console.log(result)
   });
});
```
