### ISSUE TITLE
D-Feet throws an exception when Introspecting

### ISSUE THREAD

**Issue by cybex-jmclaughlin** [sidorares/node-dbus#76]
I am trying to create a d-bus service using example/service/server2.js as a guide. It mostly works, but I found when I use D-Feet to Introspect the service, it throws a DBus exception “GDBus.Error:org.freedesktop.DBus.Error.UnknownService: Uh oh oh (36)” I thought this might be an issue with my code, so I tried running ‘node ./server2.js’ right from the example/service directory and got the same exception from D-Feet. 

After some debugging I found that this exception is thrown in bus.js inside the message event handler ```this.connection.on(‘message’, ...```. What appears to be happening is D-Feet is invoking the Introspect method with msg.path set to “/“, and this path is not found in the list of exportedObjects.  It looks like D-Feet invokes the Introspect method multiple times at each level of the msg.path hierarchy. I.E. the first Introspect method has msg.path set to ‘/‘, the next has msg.path set to ‘/com’, then ‘/com/github’, ‘/com/github/sidorares’ and finally ‘/com/github/sidorares/1’. I found that if I move the call to ```stdDbusIfaces(msg, self)``` before the check to see if the ```msg.path``` is in the ```self.exportedObjects[]``` list, then D-Feet introspection works perfectly:
```
diff --git a/lib/bus.js b/lib/bus.js
index cc8f482..a0a31fe 100644
--- a/lib/bus.js
+++ b/lib/bus.js
@@ -118,13 +118,13 @@ module.exports = function bus(conn, opts) {
            self.signals.emit(self.mangle(msg), msg.body, msg.signature);
        } else { // methodCall
 
+           if (stdDbusIfaces(msg, self))
+               return;
+
            // exported interfaces handlers
            var obj, iface, impl;
            if (obj = self.exportedObjects[msg.path]) {
 
-               if (stdDbusIfaces(msg, self))
-                   return;
-
                if (iface = obj[msg['interface']]) {
                    // now we are ready to serve msg.member
                    impl = iface[1];
```
From looking at the stdifaces.js code, I don't think this will cause much of a problem--but of course you would know better than I.  Let me know what you think.

**Comment by sidorares** [comment]
hm, looks like it should be where you moved it .
Another solution would be to pre-populate exportedObjects with `org.freedesktop.DBus.Introspect` and `org.freedesktop.DBus.Properties` handlers alongside with user-supplied services so it's not a special first step to check if it's a request for std interface

**Comment by sidorares** [comment]
I'll do more tests later today and try to confirm, thanks @cybex-jmclaughlin !

**Comment by sidorares** [comment]
looks ok to me. Can you submit pr so it'll be your commit?

**Comment by johannesjo** [comment]
I get the same error when using this example: 
https://github.com/sidorares/node-dbus/blob/master/examples/service-signals.js
