### ISSUE TITLE
Getting EPIPE errors before on connect event occurs.

### ISSUE THREAD

**Issue by mkcybi** [sidorares/node-dbus#82]
We're trying to connect to the system bus and intermittently we get an EPIPE error.  Is there any way we can debug these issues?

When we start to use strace to capture the pipe error - it goes away.

The pipe breaks before the connection occurs.  Why would the pipe break before we've gotten a chance to write to it?

**Comment by sidorares** [comment]
not sure where to start.
What's your os and hardware?

**Comment by mkcybi** [comment]
os is yocto linux running beaglebone black.

Further - when we wait for the connection to emit "connected" event then start talking to the dbus - we don't ever get the EPIPE error.

The workaround uses promises to wait for the bus.connected event before we start initializing our services.  We don't understand why this would help - because it seems node-dbus seems to buffer the messages and then only writes them on being connected.

**Comment by sidorares** [comment]
yes, I would expect memory growth in js land if lot's of data pushed to a bus before it's connected

**Comment by sidorares** [comment]
actually, probably I should add pause/resume logic in here: https://github.com/sidorares/node-dbus/blob/master/index.js#L112

**Comment by sidorares** [comment]
is that a session  bus? Might be an issue of abstract-socket. In standard networking node usually buffers data in memory if it can't be sent immediately

**Comment by mkcybi** [comment]
It's not session bus it's the system bus.  But it's right at startup - the system bus essentially just came up.

**Comment by mkcybi** [comment]
Follow up:  We were able to fix the problem by bumping up yocto's dbus package from 1.8.10 to 1.8.16.

I'm closing the issue.
