### ISSUE TITLE
Is there some synchronous API

### ISSUE THREAD

**Issue by zhangtianye** [sidorares/node-dbus#83]
There are many asynchronous API in dbus-native and it's good, but it's not vere useful if the code need to deal with complex logic, sometimes I need some synchronous API,what can I do if I want this?

**Comment by sidorares** [comment]
you can use [bluebird.promisify](https://github.com/petkaantonov/bluebird/blob/master/API.md#promisepromisifyfunction-nodefunction--dynamic-receiver---function) to convert node CPS-style callbacks into promise-based flow and use it together with [tj/co](https://github.com/tj/co) for a sync-like syntax. It would look like this:

```js
   // assume you already promisified service "obj"
   co(function *() {
      var data1 = yield obj.getSomeData(1, 2, 3);
      var data2 = yield obj.someAnotherDbusMethod(data1);
      console.log(data2);
  });
```
In future releases I might make async functions return promises in addition to accepting callbacks
Note that this is still syntax sugar and order of execution is determined by order of messages client and dbus daemon send to each other. True blocking sync messages support is not going to happen here.
