### ISSUE TITLE
About parameter type of methods.

### ISSUE THREAD

**Issue by SHCPU** [sidorares/node-dbus#84]
Can you tell me how to send data to the methods of interface?
method:
client_resquest(int32 action_id,Array of [Byte] input_garray)>>(Array of [Byte] output_garray,int32 result)
I want to send data: 1, "/home/xxx" to this method。
code:

```js
resource.getInterface('/org/freedesktop/Test', 'org.freedesktop.Test', function(err, res) {
	console.log(err, res);
	if(err){
		console.log("err>>>",err);
	}else {
		console.info("Get the interface!\n");
	
	 res.client_request(1, "/home/xxx" function(err, i1, i2){
			console.log("---ok---");
		});
	}
});
```

**Comment by sidorares** [comment]
your code should work just fine, do you get any errors?

**Comment by SHCPU** [comment]
Yes, this is error message：
/home/xxx/Desktop/Resource/node_modules/dbus-native/node_modules/xml2js/lib/xml2js.js:216
          throw ex;
                ^
Error: Data: / was not of type number

**Comment by sidorares** [comment]
could you try   `res.client_request(1, "/home/xxx".split('').map(function(s) {return s.charCodeAt(0);}),  function(err, i1, i2) {...} )` so that you send array instead of string

**Comment by SHCPU** [comment]
Thank you, this error was resolved, but the server received the data is not expected to.
Message: Opening location, old: (none), new: file:///home/xxxchar_
The right result should be this，Opening location, old: (none), new: file:///home/xxx
The end of the string is char_

**Comment by sidorares** [comment]
is your server also based on node-dbus? Can you paste server code?

**Comment by SHCPU** [comment]
Server is not based on node-dbus.Server based on glibc,I wrote a client with glibc, the result is
Opening location, old: (none), new: file:///home/xxx

**Comment by sidorares** [comment]
can you post full client code? That "char_" appended to array looks very strange, I can't see how client could add it (maybe server expect terminating 0 for some reason? Try to push 0 to array of char codes )

**Comment by SHCPU** [comment]
The full code:
var dbus = require('dbus-native');
var bus = dbus.sessionBus();
var resource = bus.getService('org.freedesktop.Test');
bus.connection.on('message', console.log);

resource.getInterface('/org/freedesktop/Test', 'org.freedesktop.Test', function(err, res) {
	console.log(err, res);
	if(err){
		console.log("err>>>",err);
	}else {
		console.info("Get the interface!\n");
	
	 res.client_request(1, "/home/xxx".split('').map(function(s) {return s.charCodeAt(0);}), function(err, i1, i2){
			console.log(i1,i2);
			console.log("console ok");
		});
	}
});

**Comment by sidorares** [comment]
Try to add terminating zero:

```js
var dbus = require('dbus-native');
var bus = dbus.sessionBus();
var resource = bus.getService('org.freedesktop.Test');
bus.connection.on('message', console.log);

resource.getInterface('/org/freedesktop/Test', 'org.freedesktop.Test', function(err, res) {
    console.log(err, res);
    if(err){
        console.log("err>>>",err);
    }else {
        console.info("Get the interface!\n");

     var filename =  "/home/xxx".split('').map(function(s) {return s.charCodeAt(0);};
     filename.push(0); // !!!!
     res.client_request(1, filename), function(err, i1, i2){
            console.log(i1,i2);
            console.log("console ok");
        });
    }
});
```

**Comment by SHCPU** [comment]
Thank you, as you say this problem。
There is no problem with the results.

**Comment by sidorares** [comment]
no problems!
