### ISSUE TITLE
How to quit the program after run out my code?

### ISSUE THREAD

**Issue by zhangtianye** [sidorares/node-dbus#87]
Hi,after I run out the code, the program can't finish itself.
Such as the example "hello" you give me.
What can I do if I want to quit the program?

**Comment by sidorares** [comment]
Hi! In node event loop runs until there are active handles ( such as timers or file descriptors )
With "hello" example you need to close bus connection using `bus.end()` method ( see https://github.com/sidorares/node-dbus/blob/master/index.js#L85 )

**Comment by zhangtianye** [comment]
Here is my code:

var Dbus = require('dbus-native');
var systemBus = Dbus.systemBus();
var Wireless_Enable_Change = function(){
	systemBus.getService('org.freedesktop.NetworkManager').getInterface(
	'/org/freedesktop/NetworkManager',
	'org.freedesktop.NetworkManager', function(err, NM) {
		NM.WirelessEnabled(function(err,Is_Enable){	
			if(err){
				console.log('err' + err);
			}else{
				systemBus.getService('org.freedesktop.NetworkManager').getInterface(
				'/org/freedesktop/NetworkManager',
				'org.freedesktop.DBus.Properties', function(err, NM_DBus) {
					NM_DBus.Set('org.freedesktop.NetworkManager','WirelessEnabled',['b',!Is_Enable],function(err){	
						if(err)
							console.log(err);
						//	console.log(JSON.stringify(Dbus));
						//	console.log(JSON.stringify(systemBus));
						Dbus.end();
					});
				});
			}
		});
	});
};
Wireless_Enable_Change();

When I use Dbus.end(),I failed.Can you help me how to use it rightly?

**Comment by sidorares** [comment]
You need to call `systemBus.end()`

**Comment by zhangtianye** [comment]
I used. Here is my code, but failed:

var Dbus = require('dbus-native');
var systemBus = Dbus.systemBus();
var Wireless_Enable_Change = function(){
	systemBus.getService('org.freedesktop.NetworkManager').getInterface(
	'/org/freedesktop/NetworkManager',
	'org.freedesktop.NetworkManager', function(err, NM) {
		NM.WirelessEnabled(function(err,Is_Enable){	
			if(err){
				console.log('err' + err);
			}else{
				systemBus.getService('org.freedesktop.NetworkManager').getInterface(
				'/org/freedesktop/NetworkManager',
				'org.freedesktop.DBus.Properties', function(err, NM_DBus) {
					NM_DBus.Set('org.freedesktop.NetworkManager','WirelessEnabled',['b',!Is_Enable],function(err){	
						if(err)
							console.log(err);
						//	console.log(JSON.stringify(Dbus));
						//	console.log(JSON.stringify(systemBus));
						systemBus.end();
					});
				});
			}
		});
	});
};
Wireless_Enable_Change();

**Comment by zhangtianye** [comment]
I used systemBus.end(); ,but failed. Is there some ways I can?

**Comment by sidorares** [comment]
what exactly failed?

**Comment by zhangtianye** [comment]
![2015-07-08 23 51 28](https://cloud.githubusercontent.com/assets/7447937/8575010/4aa41bea-25cc-11e5-88ca-36b04a7de74d.png)
Here is my error

**Comment by sidorares** [comment]
sorry that must be `bus.connection` I'll probably add `.end()` to a bus client as well.

```js
var dbus = require('dbus-native');

var systemBus = dbus.systemBus();
setTimeout(function() {
  console.log('closing dbus connection');
  systemBus.connection.end();
}, 1000);
```

connection is an object representing low level messaging - you can only send message to it via `.message(data); ` or receive messages using `.on('message', function(msg) {})`. Bus is a higher level wrapper - it manages RPC calls by matching message ids to callbacks + some more extra functionality.

**Comment by zhangtianye** [comment]
Thanks
