### ISSUE TITLE
Abstract-socket prevent from being truly native

### ISSUE THREAD

**Issue by sdumetz** [sidorares/node-dbus#92]
the abstract-socket dependency is compiled. It goes against this module being truly javascript-native.

Why does it matter? I use [electron](https://github.com/atom/electron) and module recompilation is quite a pain in numerous cases.

While i've seen abstract sockets before, I have no idea if a pure js + native core modules implementation would be possible?

**Comment by sidorares** [comment]
No, native core does not support abstract sockets. Its currently in optional dependencies and it's still possible to use module if  abstract-socket is not installed.

Usually system bus is exposed with unix socket and session bus - using  abstract socket address

**Comment by jrobeson** [comment]
is anything going to be done on this issue?

**Comment by sidorares** [comment]
No, unless abstract sockets are supported by core node ( it's relatively trivial change, Python for example have it in core networking ) but given that userland module works well and that is linux-only functionality it's very unlikely to happen. As a workaround we could include another dependency - `socat` binary installed locally, and pipe to socat process which would forward stdin to linux abstract socket, bu I think not worth effort.

**Comment by sidorares** [comment]
actually there are some changes in libuv that might allow abstract sockets ( not expecting zero-terminated string as input ). I'll do some more research and reopen if find anything

**Comment by sidorares** [comment]
https://github.com/joyent/libuv/pull/1497
https://github.com/joyent/libuv/issues/797
https://github.com/joyent/libuv/issues/1486
