### ISSUE TITLE
Connecting to peer raises warning

### ISSUE THREAD

**Issue by mspanc** [sidorares/node-dbus#98]
I need to use DBus to communicate without dbus-daemon (2 processes talk to each other directly). I've created created basic DBus server in the Vala app

```vala
static int main(string[] argv) {       
  var dbus_server = new DBusServer.sync("tcp:host=localhost,port=12345", DBusServerFlags.AUTHENTICATION_ALLOW_ANONYMOUS, "82B55E5C9D9C11E5ACA2E04969A460B9");
  dbus_server.start();
  var mainloop = new GLib.MainLoop();
  mainloop.run();
  return 0;
}
```

Then I connect from dbus-native:

```js
const dbus = require('dbus-native');

var dbusConn = dbus.createConnection({
  host: "127.0.0.1",
  port: 12345,
});
```

And the server process always raises warning:

```
(process:71311): GLib-GIO-WARNING **: Malformed data '4f1a540c4e6bf94f6ca79eb6d5929c4eb6b8969c909b088ca6e328cffa7e57b88c3a2b0b'
```

The hex string appears to be random.

The connection works anyway, but it's still unexpected behaviour.

**Comment by jrobeson** [comment]
and the equivalent in vala for your dbus-native example shows no such error? you probably need to trace what  is actually being sent.

**Comment by mspanc** [comment]
It seems that it was because it tried to authenticate while it should treat such connection as not requiring authentication. I've disabled authentication in the client and it works fine.
